vich_uploader:
    db_driver: orm

    mappings:
        candidate_cv:
            uri_prefix: '/uploads/images/candidat'
            upload_destination: '%kernel.project_dir%/public/uploads/images/candidat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute

