vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
    metadata:
        type: attribute

