vich_uploader:
    db_driver: orm

    mappings:
        candidate_cv:
            uri_prefix: 'app.path.candidate_cv'
            upload_destination: '%kernel.project_dir%/public%app.path.candidat_cv%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
    metadata:
        type: attribute

